export const SIDEBAR_OPEN = "SIDEBAR_OPEN";   //for sidebar-small devices
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";   //for sidebar-small devices
export const GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN";   //for all the products
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";  //for all the products
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";   //for all the products
export const GET_SINGLE_PRODUCT_BEGIN = "GET_SINGLE_PRODUCT_BEGIN";   //for single product page
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";  //for single product page
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR";  //for single product page
export const LOAD_PRODUCTS = "LOAD_PRODUCTS"; //for filter products in the products page
export const SET_GRIDVIEW = "SET_GRIDVIEW";
export const SET_LISTVIEW = "SET_LISTVIEW";
export const UPDATE_SORT = "UPDATE_SORT";
export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const TOGGLE_CART_ITEM_AMOUNT = "TOGGLE_CART_ITEM_AMOUNT";
export const CLEAR_CART = "CLEAR_CART";
export const COUNT_CART_TOTALS = "COUNT_CART_TOTALS";
